models:
  - name: fct_navigation_edges
    columns:
      - name: edge_key
        tests:
          - unique
          - not_null

      - name: source_page
        tests:
          - not_null

      - name: target_page
        tests:
          - not_null

      - name: click_count
        tests:
          - not_null